import { Column, CreateDateColumn, Entity, PrimaryGeneratedColumn, UpdateDateColumn } from 'typeorm';

@Entity('contacts') export class Contact { @PrimaryGeneratedColumn('uuid') id: string; @Column('uuid') org_id: string; @Column('uuid') owner_id: string; @Column() first_name: string; @Column() last_name: string; @Column({nullable:true}) email: string; @Column({nullable:true}) phone: string; @Column('uuid',{nullable:true}) company_id: string; @Column({nullable:true}) position: string; @Column({nullable:true}) avatar_url: string; @Column('text',{array:true,default:'{}'}) tags: string[]; @Column('jsonb',{default:{}}) custom_fields: any; @CreateDateColumn() created_at: Date; @UpdateDateColumn() updated_at: Date; }
@Entity('companies') export class Company { @PrimaryGeneratedColumn('uuid') id: string; @Column('uuid') org_id: string; @Column('uuid') owner_id: string; @Column() name: string; @Column({nullable:true}) domain: string; @Column({nullable:true}) industry: string; @Column({nullable:true}) size: string; @Column('jsonb',{default:{}}) address: any; @Column('jsonb',{default:{}}) social_links: any; @Column('jsonb',{default:{}}) custom_fields: any; @CreateDateColumn() created_at: Date; }
@Entity('deals') export class Deal { @PrimaryGeneratedColumn('uuid') id: string; @Column('uuid') org_id: string; @Column('uuid') owner_id: string; @Column() name: string; @Column('uuid',{nullable:true}) contact_id: string; @Column('uuid',{nullable:true}) company_id: string; @Column('uuid',{nullable:true}) pipeline_id: string; @Column('uuid',{nullable:true}) stage_id: string; @Column('numeric',{precision:12,scale:2,default:0}) amount: number; @Column({default:'USD'}) currency: string; @Column('int',{default:0}) probability: number; @Column('date',{nullable:true}) expected_close_date: string; @Column({default:'open'}) status: string; @CreateDateColumn() created_at: Date; @UpdateDateColumn() updated_at: Date; }
@Entity('pipelines') export class Pipeline { @PrimaryGeneratedColumn('uuid') id: string; @Column('uuid') org_id: string; @Column() name: string; @Column({default:false}) is_default: boolean; @CreateDateColumn() created_at: Date; }
@Entity('pipeline_stages') export class PipelineStage { @PrimaryGeneratedColumn('uuid') id: string; @Column('uuid') pipeline_id: string; @Column() name: string; @Column('int') position: number; @Column({default:'#6366F1'}) color: string; @Column('int',{default:0}) probability: number; }
@Entity('activities') export class Activity { @PrimaryGeneratedColumn('uuid') id: string; @Column('uuid') org_id: string; @Column() type: string; @Column() title: string; @Column('text',{nullable:true}) body: string; @Column('timestamptz',{nullable:true}) due_date: Date; @Column('timestamptz',{nullable:true}) completed_at: Date; @Column('uuid',{nullable:true}) contact_id: string; @Column('uuid',{nullable:true}) deal_id: string; @Column('uuid',{nullable:true}) company_id: string; @Column('uuid') created_by: string; @Column('uuid',{nullable:true}) assignee_id: string; @CreateDateColumn() created_at: Date; }
@Entity('emails') export class Email { @PrimaryGeneratedColumn('uuid') id: string; @Column('uuid') org_id: string; @Column('uuid',{nullable:true}) contact_id: string; @Column() direction: string; @Column() subject: string; @Column('text',{nullable:true}) body_html: string; @Column('text',{nullable:true}) body_text: string; @Column('timestamptz',{nullable:true}) sent_at: Date; @Column('timestamptz',{nullable:true}) opened_at: Date; @Column('timestamptz',{nullable:true}) clicked_at: Date; }
