import React, { useMemo, useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { DragDropContext, Droppable, Draggable } from 'react-beautiful-dnd';
import { Avatar, Badge, Button, Card, Input, Modal, Select, Table, Tabs, Tooltip } from '@nexusone/shared-ui';
import { HrmDashboardWidget } from '../components/HrmWidgets';

const fetcher = (u: string) => fetch(u).then((r) => r.json());

export function EmployeesPage() {
  const { data=[] } = useQuery({ queryKey:['hrm-employees'], queryFn:()=>fetcher('/hrm/employees') });
  const [view, setView] = useState<'grid'|'list'>('grid');
  const [dept,setDept]=useState('all'); const [status,setStatus]=useState('all'); const [etype,setEtype]=useState('all');
  const list = useMemo(()=>data.filter((e:any)=>(dept==='all'||String(e.department_id)===dept)&&(status==='all'||e.status===status)&&(etype==='all'||e.employment_type===etype)),[data,dept,status,etype]);
  return <div className='space-y-4'><HrmDashboardWidget /><div className='flex gap-2'><Button variant={view==='grid'?'primary':'ghost'} onClick={()=>setView('grid')}>Grid</Button><Button variant={view==='list'?'primary':'ghost'} onClick={()=>setView('list')}>List</Button><div className='w-44'><Select value={dept} onValueChange={setDept} items={[{value:'all',label:'All departments'},{value:'1',label:'Engineering'}]} /></div><div className='w-40'><Select value={status} onValueChange={setStatus} items={[{value:'all',label:'All status'},{value:'active',label:'Active'},{value:'inactive',label:'Inactive'}]} /></div><div className='w-44'><Select value={etype} onValueChange={setEtype} items={[{value:'all',label:'Employment type'},{value:'full_time',label:'Full-time'},{value:'contract',label:'Contract'}]} /></div></div>{view==='grid'?<div className='grid gap-3 md:grid-cols-3'>{list.map((e:any)=><Card key={e.id}><div className='flex items-center gap-3'><Avatar name={e.full_name||e.employee_code} /><div><p className='font-semibold'>{e.full_name||e.employee_code}</p><p className='text-xs text-slate-400'>{e.employment_type} · Dept {e.department_id||'-'}</p></div><Badge>{e.status}</Badge></div><div className='mt-3 flex gap-2'><Button variant='ghost'>View profile</Button><Button variant='ghost'>Send message</Button></div></Card>)}</div>:<Table headers={['Name','Department','Status','Type','Actions']} rows={list.map((e:any)=>[e.full_name||e.employee_code,String(e.department_id||'-'),e.status,e.employment_type,'View / Message'])} />}</div>;
}

export function EmployeeProfilePage() {
  const qc = useQueryClient();
  const { data=[] } = useQuery({ queryKey:['hrm-employees'], queryFn:()=>fetcher('/hrm/employees') });
  const employee = data[0] || {};
  const mutation = useMutation({ mutationFn:(payload:any)=>fetch('/hrm/employees',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}).then(r=>r.json()), onMutate:async(payload)=>{const prev=qc.getQueryData<any[]>(['hrm-employees'])||[]; qc.setQueryData(['hrm-employees'], prev.map((e)=>e.id===payload.id?{...e,...payload}:e)); return {prev};}, onError:(_e,_p,ctx)=>ctx&&qc.setQueryData(['hrm-employees'],ctx.prev)});
  return <div className='space-y-4'><Card><div className='flex items-center gap-3'><Avatar name={employee.full_name||'Employee'} /><div><h2 className='text-xl font-semibold'>{employee.full_name||'Employee Name'}</h2><p className='text-slate-400'>{employee.designation_id||'Role'} · Dept {employee.department_id||'-'}</p></div><Badge>{employee.status||'active'}</Badge><Button className='ml-auto' onClick={()=>mutation.mutate({id:employee.id, status:'active'})}>Save inline edits</Button></div></Card><Tabs tabs={[{value:'overview',label:'Overview',content:<Card><p>Personal info, emergency contact, manager info</p></Card>},{value:'documents',label:'Documents',content:<Card>Documents</Card>},{value:'leave',label:'Leave',content:<Card>Leave history</Card>},{value:'attendance',label:'Attendance',content:<Card>Attendance logs</Card>},{value:'payroll',label:'Payroll',content:<Card>Payroll records</Card>},{value:'reviews',label:'Reviews',content:<Card>Performance reviews</Card>}]} /></div>;
}

export function LeavePage() { const {data=[]}=useQuery({queryKey:['leave'],queryFn:()=>fetcher('/hrm/leave-requests')}); const [open,setOpen]=useState(false); return <div className='space-y-4'><Card>Calendar view (team leave)</Card><Table headers={['From','To','Days','Status']} rows={data.map((r:any)=>[r.from_date,r.to_date,String(r.days),r.status])} /><Modal title='Request Leave' trigger={<Button onClick={()=>setOpen(true)}>Request Leave</Button>}><div className='space-y-2'><Input placeholder='Leave type id' /><Input placeholder='Reason' /><Button>Submit</Button></div></Modal><Card><h3 className='mb-2 font-semibold'>Manager approval queue</h3><div className='flex gap-2'><Button>Approve</Button><Button variant='ghost'>Reject</Button></div></Card></div>; }

export function AttendancePage() { return <div className='space-y-4'><Card><h3>Today's status</h3><div className='mt-2 flex gap-2'><Button>Check In</Button><Button variant='ghost'>Check Out</Button></div></Card><Card>Monthly attendance heatmap</Card><Card>Summary: present, absent, late, overtime hours</Card></div>; }

export function PayrollPage() { return <div className='space-y-4'><Card>Monthly payslip cards</Card><Modal title='Payslip detail' trigger={<Button>Open Payslip</Button>}><p>Earnings and deductions breakdown</p><Button>Download PDF</Button></Modal></div>; }

export function RecruitmentPage() {
  const [cols, setCols] = useState<any>({ applied:[{id:'a1',name:'Jane',score:78,summary:'Strong fit'}], screening:[{id:'a2',name:'Max',score:62,summary:'Needs deeper interview'}], interview:[], offer:[], hired:[], rejected:[] });
  const onDragEnd=(r:any)=>{ if(!r.destination) return; const src=[...cols[r.source.droppableId]]; const [item]=src.splice(r.source.index,1); const dst=[...cols[r.destination.droppableId]]; dst.splice(r.destination.index,0,item); setCols({...cols,[r.source.droppableId]:src,[r.destination.droppableId]:dst}); };
  return <div className='space-y-4'><Card>Jobs list with open positions and applicant counts</Card><Card><h3 className='mb-2 font-semibold'>Applicants Kanban</h3><DragDropContext onDragEnd={onDragEnd}><div className='grid gap-3 md:grid-cols-3 lg:grid-cols-6'>{Object.keys(cols).map((k)=><Droppable droppableId={k} key={k}>{(p)=><div ref={p.innerRef} {...p.droppableProps} className='min-h-40 rounded bg-slate-800 p-2'><p className='mb-2 text-xs uppercase text-slate-400'>{k}</p>{cols[k].map((a:any,i:number)=><Draggable draggableId={a.id} index={i} key={a.id}>{(pp)=><div ref={pp.innerRef} {...pp.draggableProps} {...pp.dragHandleProps} className='mb-2 rounded bg-slate-700 p-2'><p className='font-medium'>{a.name}</p><Tooltip content={a.summary}><span className={`text-xs ${a.score>=75?'text-emerald-300':a.score>=50?'text-amber-300':'text-rose-300'}`}>AI {a.score}</span></Tooltip><div className='mt-2'><Button variant='ghost'>AI Screen</Button></div></div>}</Draggable>)}{p.placeholder}</div>}</Droppable>)}</div></DragDropContext></Card></div>;
}
