events {}
http {
  upstream web { server web:3000; }
  upstream api_gateway { server api-gateway:4000; }
  upstream comm_service { server comm-service:8001; }
  upstream hrm_service { server hrm-service:8002; }
  upstream crm_service { server crm-service:8003; }

  server {
    listen 80;

    location / {
      proxy_pass http://web;
    }

    location /api/ {
      proxy_pass http://api_gateway/;
    }

    location /comm/ {
      proxy_pass http://comm_service/;
    }

    location /hrm/ {
      proxy_pass http://hrm_service/;
    }

    location /crm/ {
      proxy_pass http://crm_service/;
    }
  }
}
