import React, { useMemo, useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { motion, AnimatePresence } from 'framer-motion';
import { DragDropContext, Draggable, Droppable } from 'react-beautiful-dnd';
import { Area, AreaChart, Cell, Pie, PieChart, ResponsiveContainer, Tooltip as RTooltip, XAxis, YAxis } from 'recharts';
import { Avatar, Badge, Button, Card, Input, Modal, Table, Tabs, Tooltip } from '@nexusone/shared-ui';

const f=(u:string)=>fetch(u).then(r=>r.json());

export function CrmDashboardPage(){
  const deals=[{stage:'Prospect',value:14},{stage:'Qualified',value:10},{stage:'Proposal',value:8},{stage:'Won',value:6}];
  const trend=[{d:'W1',v:21},{d:'W2',v:28},{d:'W3',v:25},{d:'W4',v:34}];
  return <div className='space-y-4'><div className='grid gap-3 md:grid-cols-4'><Card><p className='text-xs text-slate-400'>Revenue this month</p><p className='text-2xl font-semibold'>$148,200</p><Badge>+12.4% vs last month</Badge></Card><Card className='md:col-span-2'><p className='mb-2 text-sm'>Deals by stage</p><div className='h-44'><ResponsiveContainer><PieChart><Pie data={deals} dataKey='value' nameKey='stage' innerRadius={40} outerRadius={70}>{['#6366F1','#8B5CF6','#10B981','#F59E0B'].map((c,i)=><Cell key={i} fill={c} />)}</Pie><RTooltip /></PieChart></ResponsiveContainer></div></Card><Card><p className='text-sm font-semibold'>Activities due today</p><ul className='mt-2 text-sm text-slate-300'><li>Call ACME procurement</li><li>Send proposal to Globex</li><li>Demo for Umbrella</li></ul></Card></div><div className='grid gap-3 md:grid-cols-2'><Card><p className='mb-2 text-sm font-semibold'>Top deals by value</p><Table headers={['Deal','Value']} rows={[['ACME Renewal','$42,000'],['Globex Expansion','$35,500'],['Initech Upgrade','$29,800']]} /></Card><Card><p className='mb-2 text-sm font-semibold'>Win rate trend</p><div className='h-52'><ResponsiveContainer><AreaChart data={trend}><XAxis dataKey='d' stroke='#94a3b8' /><YAxis stroke='#94a3b8' /><RTooltip /><Area type='monotone' dataKey='v' stroke='#6366F1' fill='#6366F155' /></AreaChart></ResponsiveContainer></div></Card></div></div>;
}

function ContactPanel({item,onClose}:{item:any,onClose:()=>void}){return <AnimatePresence>{item&&<motion.aside initial={{x:380}} animate={{x:0}} exit={{x:380}} className='fixed right-0 top-0 z-30 h-full w-[380px] border-l border-slate-700 bg-slate-900 p-4'><div className='flex items-center justify-between'><h3 className='font-semibold'>{item.name}</h3><Button variant='ghost' onClick={onClose}>Close</Button></div><p className='text-sm text-slate-400'>{item.email}</p><div className='mt-3'><Button>AI Enrich</Button></div><div className='mt-4'><Tabs tabs={[{value:'act',label:'Activities',content:<Card>Activity timeline</Card>},{value:'deals',label:'Deals',content:<Card>Related deals</Card>},{value:'emails',label:'Emails',content:<Card>Email timeline</Card>}]} /></div></motion.aside>}</AnimatePresence>}

export function ContactsPage(){
  const {data=[]}=useQuery({queryKey:['crm-contacts'],queryFn:()=>f('/crm/contacts')});
  const [q,setQ]=useState(''); const [selected,setSelected]=useState<any[]>([]); const [open,setOpen]=useState<any>(null);
  const rows=useMemo(()=>data.filter((c:any)=>`${c.first_name} ${c.last_name}`.toLowerCase().includes(q.toLowerCase())),[data,q]);
  return <div className='space-y-3'><div className='flex gap-2'><Input placeholder='Filter contacts' value={q} onChange={(e:any)=>setQ(e.target.value)} />{selected.length>0&&<Card className='flex items-center gap-2 p-2'><span>{selected.length} selected</span><Button variant='ghost'>Bulk tag</Button><Button variant='ghost'>Bulk assign</Button></Card>}</div><Table headers={['Name','Company','Email','Phone','Owner','Last Activity','Tags']} rows={rows.map((c:any)=>[`${c.first_name} ${c.last_name}`,c.company_id||'-',c.email||'-',c.phone||'-',c.owner_id||'-','Today',(c.tags||[]).join(', ')||'-'])} /><div className='grid gap-2'>{rows.map((c:any)=><button key={c.id} className='rounded bg-slate-800 p-2 text-left' onClick={()=>setOpen({name:`${c.first_name} ${c.last_name}`,email:c.email})}>{c.first_name} {c.last_name}</button>)}</div><ContactPanel item={open} onClose={()=>setOpen(null)} /></div>;
}

export function CompaniesPage(){ const {data=[]}=useQuery({queryKey:['crm-companies'],queryFn:()=>f('/crm/companies')}); return <div className='space-y-3'><Table headers={['Logo','Name','Domain','Contacts','Open Deals']} rows={data.map((c:any)=>[`https://www.google.com/s2/favicons?domain=${c.domain||'example.com'}`,c.name,c.domain||'-',String(c.contacts_count||0),String(c.open_deals_count||0)])} /></div>; }

export function PipelinePage(){
  const [cols,setCols]=useState<any>({prospect:[{id:'d1',name:'ACME',company:'Acme Inc',amount:42000,owner:'AL',close:'2026-06-02',prob:42}],qualified:[{id:'d2',name:'Globex',company:'Globex',amount:28000,owner:'SN',close:'2026-06-19',prob:61}],proposal:[],won:[]});
  const onDragEnd=(r:any)=>{if(!r.destination)return;const src=[...cols[r.source.droppableId]];const [it]=src.splice(r.source.index,1);const dst=[...cols[r.destination.droppableId]];dst.splice(r.destination.index,0,it);setCols({...cols,[r.source.droppableId]:src,[r.destination.droppableId]:dst});};
  return <div className='space-y-3'><div className='flex gap-2'><Input placeholder='Owner filter' /><Input placeholder='Amount range' /><Input placeholder='Close date range' /></div><DragDropContext onDragEnd={onDragEnd}><div className='grid gap-3 md:grid-cols-2 lg:grid-cols-4'>{Object.keys(cols).map((k)=><Droppable droppableId={k} key={k}>{(p)=><div ref={p.innerRef} {...p.droppableProps} className='rounded bg-slate-800 p-2'><div className='mb-2 flex items-center justify-between'><p className='text-xs uppercase text-slate-400'>{k}</p><Button variant='ghost'>+ Deal</Button></div>{cols[k].map((d:any,i:number)=><Draggable draggableId={d.id} index={i} key={d.id}>{(pp)=><Card ref={pp.innerRef as any} {...pp.draggableProps} {...pp.dragHandleProps} className='mb-2'><p className='font-medium'>{d.name}</p><p className='text-xs text-slate-400'>{d.company}</p><p className='mt-1 text-sm'>${d.amount.toLocaleString()}</p><div className='mt-1 flex items-center gap-2'><Avatar name={d.owner} /><span className='text-xs'>{d.close}</span></div><div className='mt-2 h-1 rounded bg-slate-700'><div className='h-1 rounded bg-indigo-500' style={{width:`${d.prob}%`}} /></div><Tooltip content='AI forecast details'><Button className='mt-2' variant='ghost'>AI Forecast</Button></Tooltip></Card>}</Draggable>)}{p.placeholder}</div>}</Droppable>)}</div></DragDropContext></div>;
}

export function ActivitiesPage(){ return <div className='space-y-3'><Card><h3 className='font-semibold'>Timeline</h3><ul className='mt-2 text-sm'><li>📞 Call - Follow-up with ACME</li><li>✉️ Email - Proposal sent</li><li>📅 Meeting - Discovery with Globex</li><li>✏️ Note - Budget concerns</li></ul></Card><Modal title='Quick log activity' trigger={<Button>Log Activity</Button>}><div className='space-y-2'><Input placeholder='Type (call/email/meeting/note/task)' /><Input placeholder='Title' /><Input placeholder='Notes' /><Input placeholder='Contact/Deal link' /><Input placeholder='Due date' /><Button>Save</Button></div></Modal></div>; }

export function GlobalSearchResults(){ const [q,setQ]=useState(''); const [idx,setIdx]=useState(0); const groups:any={Contacts:['Alice Nguyen','Sam Patel'],Companies:['Acme Inc'],Deals:['ACME Renewal'],Messages:['budget mentioned in thread'],Employees:['Dana Lee']}; const flat=Object.entries(groups).flatMap(([t,arr]:any)=>arr.map((v:string)=>({t,v}))); return <Card><Input value={q} onChange={(e:any)=>setQ(e.target.value)} onKeyDown={(e:any)=>{if(e.key==='ArrowDown')setIdx((i)=>Math.min(i+1,flat.length-1));if(e.key==='ArrowUp')setIdx((i)=>Math.max(i-1,0));if(e.key==='Enter') alert(`Open ${flat[idx]?.v}`);}} placeholder='Global fuzzy search...' /><div className='mt-3 space-y-2'>{Object.entries(groups).map(([g,arr]:any)=><div key={g}><p className='text-xs uppercase text-slate-400'>{g}</p>{arr.filter((x:string)=>x.toLowerCase().includes(q.toLowerCase())).map((x:string)=>{const i=flat.findIndex((f:any)=>f.v===x&&f.t===g); const m=x.replace(new RegExp(`(${q})`,'ig'),'<mark>$1</mark>'); return <div key={x} className={`rounded px-2 py-1 ${idx===i?'bg-indigo-500/30':''}`} dangerouslySetInnerHTML={{__html:m}} />;})}</div>)}</div></Card>; }
